name: Build e Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Injetar config.json dos clientes
        run: |
          mkdir -p clientes/5-AdvBrasil
          echo "${{ secrets.CLIENT_CONFIG_ADVBRASIL }}" | base64 -d > clientes/5-AdvBrasil/config.json

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/agente-de-atendimento:latest
